import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Container from '@mui/material/Container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Container maxWidth="sm" className="full-height">
                    {children}
                </Container>
            </body>
        </html>
    );
}
